### ISSUE TITLE
JSON detection not working

### ISSUE THREAD

**Issue by LouTerrailloune** [fightbulc/simplon_twitter#1]
A JSON response does not always start with `{`, when the result is an array the first char is `[`. (for exemple, when calling `statuses/user_timeline`)
Anyway, checking the headers is a better way to detect the content type.

**Comment by fightbulc** [comment]
True true. Will be fixed. Thanks, Lou.

**Comment by fightbulc** [comment]
fixed with https://github.com/fightbulc/simplon_twitter/releases/tag/0.2.4
